apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: goldmane
    k8s-app: goldmane
  name: goldmane
  namespace: kube-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: goldmane
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: goldmane
        k8s-app: goldmane
      name: goldmane
    spec:
      containers:
      - env:
        - name: LOG_LEVEL
          value: INFO
        - name: PORT
          value: "7443"
        - name: SERVER_CERT_PATH
          value: /goldmane-key-pair/tls.crt
        - name: SERVER_KEY_PATH
          value: /goldmane-key-pair/tls.key
        - name: CA_CERT_PATH
          value: /etc/pki/tls/certs/frozen-tutorials.crt
        - name: PUSH_URL
          value: https://guardian.kube-system.svc.cluster.local:443/api/v1/flows/bulk
        - name: FILE_CONFIG_PATH
          value: /config/config.json
        - name: HEALTH_ENABLED
          value: "true"
        image: docker.io/calico/goldmane:v3.30.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /health
            - -live
          failureThreshold: 3
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 5
        name: goldmane
        readinessProbe:
          exec:
            command:
            - /health
            - -ready
          failureThreshold: 3
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          runAsGroup: 10001
          runAsNonRoot: true
          runAsUser: 10001
          seccompProfile:
            type: RuntimeDefault
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: config
          readOnly: true
        - mountPath: /etc/pki/tls/certs
          name: goldmane-ca-bundle
          readOnly: true
        - mountPath: /goldmane-key-pair
          name: goldmane-key-pair
          readOnly: true
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: goldmane
      serviceAccountName: goldmane
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
      - key: CriticalAddonsOnly
        operator: Exists
      volumes:
      - configMap:
          defaultMode: 420
          name: goldmane
        name: config
      - configMap:
          defaultMode: 420
          name: goldmane-ca-bundle
        name: goldmane-ca-bundle
      - name: goldmane-key-pair
        secret:
          defaultMode: 420
          secretName: goldmane-key-pair